### ISSUE TITLE
感觉 v3.8.1 可以往 mihomo 提交pr了 

### ISSUE THREAD

**Issue by snakem982** [enfein/mieru#172]
我在 mihomo 中集成了 v3.8.1 的 mieru
经过测试没啥问题，挺流畅的，TUN模式下功能也正常
参照了作者上次在 mihomo 提 pr 时的代码 [mieru.go](https://github.com/snakem982/mihomo/blob/moshen/adapter/outbound/mieru.go)
测试客户端用的是 [Pandora-Box 预览版](https://github.com/snakem982/Pandora-Box/releases/tag/Prerelease-main)
配置是作者提供的示例
```yaml
proxies:
    - name: "mieru"
      type: mieru
      server: 1.2.3.4
      port: 9966
      transport: TCP
      username: test
      password: test
```
